config/routes.rb
Rails.application.routes.draw do
  get 'posts/dashboard'
  get 'posts', to: 'posts#index'
  get 'posts/create'

  root 'posts#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :image_url,:content, presence: true
  validates :image_url, format: {with: /\.(png|jpg)\Z/i} 
  before_save :censor

  def censor
    self.content = self.content.gsub('spoiler', '')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: "desafiovamoscontodo", password: "XAHTJEAS23123%23", only: :dashboard
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def dashboard
  end

  def create
    @post = Post.create(title: params[:title], image_url: params[:image_url], content: params[:content])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/create.html.erb
<div class="container">
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %>
      prohibited this post from being published:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      <p><%= link_to 'Try again', posts_dashboard_path %></p>
    </div>
  <% else%>
    <h1> Your post was created successfully! </h1>
    <p>Check your recently created post <%= link_to 'here', posts_path %></p>
  <% end %>
</div>

app/views/posts/dashboard.html.erb
<div class="container"><h1> Create your post </h1></div>
<div class="container">
    <form method="get" action="/posts/create" id="create_posts">
    <div class="form-group">
      <label for="title">Title</label>
      <input name="title" class="form-control" id="title" arial-describedby="titleHelp" placeholder="Enter title">
    </div>

    <div class="form-group">
      <label for="image">Image</label>
      <input name="image_url" type="text" class="form-control" placeholder="Enter Image URL">
    </div>

    <div class="form-group">
      <label for="content">Content</label>
      <textarea name="content" class="form-control"></textarea>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
    </form>
    <br>
    <p> Are you having second thoughts about creating a post?</p>
    <p><%= link_to 'Return Home', root_path  %> </p>
</div>

app/views/posts/index.html.erb
<div class="container">
  <h1>Blog Posts</h1>
  <table class="table">
    <tr>
      <th>Title</th>
      <th>Posted In</th>
      <th>Image</th>
      <th>Content</th>
    </tr>
    <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.created_at %></td>
      <td><img src='<%= post.image_url %>' width="100"></td>
      <td><%= post.content %></td>
    </tr>
    <% end %>
  </table>
  <p>Create your own post <%= link_to "here", posts_dashboard_path %>!</p>
</div>